require("bogdan")

require("plugins/comment")
require("plugins/nvim-tree")
require("plugins/lualine")
require("plugins/telescope")
require("plugins/nvim-cmp")
require("plugins/lsp/mason")
require("plugins/lsp/lspsaga")
require("plugins/lsp/lspconfig")
-- require("plugins/nvim-treesitter")
require("plugins/nvim-null-ls")
