require("bogdan")

require("plugins/comment")
require("plugins/lualine")
require("plugins/nvim-treesitter")
require("plugins/nvim-tree")
require("plugins/nvim-cmp")
require("plugins/nvim-lspconfig")
require("plugins/nvim-telescope")
require("plugins/nvim-null-ls")
